using UnityEngine; // Importa el espacio de nombres principal de Unity
using UnityEngine.AI; // Importa el sistema de navegaci贸n de Unity

public class EnemyMovement : MonoBehaviour
{
    // Referencia al transform del jugador para poder seguirlo
    public Transform player;
    // Referencia al componente NavMeshAgent que permite mover al enemigo usando la malla de navegaci贸n
    private NavMeshAgent navMeshAgent;

    // Start se llama una vez antes de la primera actualizaci贸n del frame
    void Start()
    {
        // Obtiene el componente NavMeshAgent del enemigo
        navMeshAgent = GetComponent<NavMeshAgent>();
    }

    // Update se llama una vez por frame
    void Update()
    {
        // Si existe una referencia al jugador, el enemigo lo sigue
        if (player != null)
        {
            // Establece la posici贸n del jugador como destino del enemigo
            navMeshAgent.SetDestination(player.position);
        }   
    }
}
